# Generated by Django 3.2.4 on 2022-04-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(db_index=True, default=None, null=True),
        ),
    ]
