# Generated by Django 3.2.13 on 2022-06-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='savings',
            field=models.BooleanField(default=False),
        ),
    ]
