# Generated by Django 3.1.7 on 2021-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rollover',
            field=models.BooleanField(default=False),
        ),
    ]
