# Generated by Django 5.2.5 on 2025-08-15 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_savings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'date'], name='idx_income_user_date'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'category', 'date'], name='idx_income_user_cat_date'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'date'], name='idx_purchase_user_date'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'category', 'date'], name='idx_purchase_user_cat_date'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['category', 'date'], name='idx_purchase_category_date'),
        ),
    ]
