# Generated by Django 3.2.4 on 2021-07-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
    ]
