# Generated by Django 3.2.4 on 2021-07-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_auto_20210715_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='income',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='amount_currency',
        ),
    ]
