# Generated by Django 5.2.5 on 2026-01-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_add_recurring_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringpurchase',
            name='merchant',
        ),
        migrations.AddField(
            model_name='recurringpurchase',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='recurringpurchase',
            name='source',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
