# Generated by Django 6.0.1 on 2026-01-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_category_id_alter_income_id_alter_purchase_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringpurchase',
            name='merchant',
        ),
        migrations.AddField(
            model_name='recurringpurchase',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='recurringpurchase',
            name='source',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
