# Generated by Django 5.2.5 on 2026-01-17 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_change_recurring_merchant_to_source_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='recurring_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='purchases.recurringpurchase'),
        ),
    ]
