# Generated by Django 5.2.5 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0008_add_recurring_purchase"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["user", "created_at"],
                name="idx_purchase_user_created",
            ),
        ),
    ]
