# Generated by Django 3.2.4 on 2021-07-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_auto_20210715_0111'),
        ('purchases', '0009_auto_20210716_2000'),
    ]

    operations = [
    ]
