# Generated by Django 3.2.4 on 2021-07-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0010_merge_0006_auto_20210715_0111_0009_auto_20210716_2000"),
    ]

    operations = []
