# Generated by Django 3.2.4 on 2021-09-01 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.DateField()),
                ('expected_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to=settings.AUTH_USER_MODEL)),
                ('yearly_budget', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='budgets.yearlybudget')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='purchases.category')),
                ('monthly_budget', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budgets.monthlybudget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to=settings.AUTH_USER_MODEL)),
                ('yearly_budget', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budgets.yearlybudget')),
            ],
        ),
        migrations.AddConstraint(
            model_name='yearlybudget',
            constraint=models.UniqueConstraint(fields=('date', 'user'), name='unique_yearlybudget'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.UniqueConstraint(fields=('date', 'user'), name='unique_monthlybudget'),
        ),
        migrations.AddConstraint(
            model_name='budgetitem',
            constraint=models.UniqueConstraint(fields=('monthly_budget', 'category', 'user'), name='unique_budgetitem'),
        ),
    ]
