# Generated by Django 3.1.7 on 2021-03-22 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.BooleanField()),
                ('date', models.DateField()),
                ('expected_income', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='budget',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='yearly_budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='budgets.yearlybudget'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='monthly_budget',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budgets.monthlybudget'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='yearly_budget',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budgets.yearlybudget'),
        ),
    ]
