# Generated by Django 3.2.4 on 2021-09-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='savings',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
