# Generated by Django 3.1.7 on 2021-03-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20210322_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlybudget',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
