# Generated by Django 5.2.5 on 2025-08-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_auto_20220115_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlybudget',
            options={'ordering': ['date']},
        ),
    ]
