# Generated by Django 3.1.7 on 2021-04-16 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20210416_2042'),
        ('budgets', '0003_yearlybudget_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='purchases.category'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='yearly_budget',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budgets.yearlybudget'),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='monthly',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='budgetitem',
            constraint=models.UniqueConstraint(fields=('monthly_budget', 'category', 'user'), name='unique_budgetitem'),
        ),
    ]
