# Generated by Django 3.2.4 on 2021-07-15 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_auto_20210416_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='monthly_budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budgets.monthlybudget'),
        ),
    ]
