# Generated by Django 5.2.5 on 2025-08-15 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_yearlybudget_options'),
        ('purchases', '0005_income_idx_income_user_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['user', 'yearly_budget', 'savings'], name='idx_bi_user_yearly_savings'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['monthly_budget', 'category', 'user'], name='idx_bi_monthly_cat_user'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['user', 'category'], name='idx_budgetitem_user_category'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['yearly_budget', 'savings'], name='idx_budgetitem_yearly_savings'),
        ),
        migrations.AddIndex(
            model_name='monthlybudget',
            index=models.Index(fields=['user', 'date'], name='idx_monthly_budget_user_date'),
        ),
        migrations.AddIndex(
            model_name='monthlybudget',
            index=models.Index(fields=['yearly_budget', 'user'], name='idx_monthly_yearly_user'),
        ),
        migrations.AddIndex(
            model_name='rollover',
            index=models.Index(fields=['user', 'yearly_budget', 'category'], name='idx_rollover_user_yearly_cat'),
        ),
        migrations.AddIndex(
            model_name='rollover',
            index=models.Index(fields=['yearly_budget', 'category'], name='idx_rollover_yearly_category'),
        ),
    ]
