# Generated by Django 5.2.5 on 2026-08-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0006_alter_budgetitem_id_alter_monthlybudget_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expense_sources", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseSourceCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_checked", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("expense_source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monthly_checks", to="budgets.expensesource")),
                ("monthly_budget", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expense_source_checks", to="budgets.monthlybudget")),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseSourceMonth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expense_source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monthly_memberships", to="budgets.expensesource")),
                ("monthly_budget", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expense_source_memberships", to="budgets.monthlybudget")),
            ],
            options={
                "ordering": ["monthly_budget__date", "expense_source__name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="expensesource",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="unique_expense_source_user_name"),
        ),
        migrations.AddIndex(
            model_name="expensesourcecheck",
            index=models.Index(fields=["monthly_budget", "expense_source"], name="idx_monthly_exp_source_chk"),
        ),
        migrations.AddConstraint(
            model_name="expensesourcecheck",
            constraint=models.UniqueConstraint(fields=("monthly_budget", "expense_source"), name="unique_monthly_expense_source_check"),
        ),
        migrations.AddIndex(
            model_name="expensesourcemonth",
            index=models.Index(fields=["monthly_budget", "expense_source"], name="idx_monthly_exp_source_member"),
        ),
        migrations.AddConstraint(
            model_name="expensesourcemonth",
            constraint=models.UniqueConstraint(fields=("monthly_budget", "expense_source"), name="unique_monthly_expense_source_membership"),
        ),
    ]
