# Generated by Django 5.2.5 on 2026-08-24

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0006_alter_budgetitem_id_alter_monthlybudget_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("user"),
                        django.db.models.functions.text.Lower("name"),
                        name="unique_expense_source_user_name",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyExpenseSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_included", models.BooleanField(default=True)),
                ("is_checked", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "expense_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_sources",
                        to="budgets.expensesource",
                    ),
                ),
                (
                    "monthly_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_expense_sources",
                        to="budgets.monthlybudget",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("monthly_budget", "expense_source"),
                        name="unique_monthly_expense_source",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(is_checked=True, checked_at__isnull=False)
                            | models.Q(is_checked=False, checked_at__isnull=True)
                        ),
                        name="monthly_expense_source_checked_at_matches_state",
                    ),
                ],
            },
        ),
    ]
