# Generated by Django 5.2.5 on 2026-08-24

import django.db.models.deletion
from django.db import migrations, models


def seed_expense_source_months(apps, schema_editor):
    ExpenseSource = apps.get_model("budgets", "ExpenseSource")
    ExpenseSourceCheck = apps.get_model("budgets", "ExpenseSourceCheck")
    ExpenseSourceMonth = apps.get_model("budgets", "ExpenseSourceMonth")
    MonthlyBudget = apps.get_model("budgets", "MonthlyBudget")

    for source in ExpenseSource.objects.all().iterator():
        if source.is_active:
            budget_ids = MonthlyBudget.objects.filter(
                user_id=source.user_id,
            ).values_list("id", flat=True)
        else:
            budget_ids = ExpenseSourceCheck.objects.filter(
                expense_source_id=source.id,
            ).values_list("monthly_budget_id", flat=True)

        ExpenseSourceMonth.objects.bulk_create(
            [
                ExpenseSourceMonth(
                    expense_source_id=source.id,
                    monthly_budget_id=budget_id,
                )
                for budget_id in budget_ids
            ],
            ignore_conflicts=True,
        )


def restore_expense_source_flags(apps, schema_editor):
    ExpenseSource = apps.get_model("budgets", "ExpenseSource")
    ExpenseSourceMonth = apps.get_model("budgets", "ExpenseSourceMonth")

    for source in ExpenseSource.objects.all().iterator():
        source.is_active = ExpenseSourceMonth.objects.filter(
            expense_source_id=source.id,
        ).exists()
        source.save(update_fields=["is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0007_expensesource_expensesourcecheck_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseSourceMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_memberships",
                        to="budgets.expensesource",
                    ),
                ),
                (
                    "monthly_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_source_memberships",
                        to="budgets.monthlybudget",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "monthly_budget__date",
                    "expense_source__name",
                    "id",
                ],
            },
        ),
        migrations.AddField(
            model_name="expensesourcecheck",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(
            seed_expense_source_months,
            restore_expense_source_flags,
        ),
        migrations.RemoveIndex(
            model_name="expensesource",
            name="idx_expense_source_active",
        ),
        migrations.RemoveField(
            model_name="expensesource",
            name="is_active",
        ),
        migrations.AddIndex(
            model_name="expensesourcemonth",
            index=models.Index(
                fields=["monthly_budget", "expense_source"],
                name="idx_monthly_exp_source_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="expensesourcemonth",
            constraint=models.UniqueConstraint(
                fields=("monthly_budget", "expense_source"),
                name="unique_monthly_expense_source_membership",
            ),
        ),
    ]
