# Generated by Django 3.2.4 on 2021-07-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0005_alter_budgetitem_monthly_budget"),
    ]

    operations = [
        migrations.RemoveField(model_name="budgetitem", name="amount",),
        migrations.RemoveField(model_name="monthlybudget", name="expected_income",),
    ]
