# Generated by Django 3.2.4 on 2021-07-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_auto_20210715_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='monthlybudget',
            name='expected_income',
        ),
        migrations.RemoveField(
            model_name='monthlybudget',
            name='expected_income_currency',
        ),
    ]
