# Generated by Django 3.2.4 on 2021-07-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_auto_20210716_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='expected_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
